{{- if eq .Values.secret.password.type "plain" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.password.name }}
type: Opaque
data:
  password: {{ .Values.secret.password.value }}
{{- end }}

{{- if eq .Values.secret.password.type "sealed" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secret.password.name }}
spec:
  encryptedData:
    password: {{ .Values.secret.password.value }}
  template:
    metadata:
      name: {{ .Values.secret.password.name }}
    type: Opaque
{{- end }}
